### ISSUE TITLE
Component Feature Layers

### ISSUE THREAD

**Issue by padawong** [CIDARLAB/Parchmint#8]
If a Component has multiple layers, in Component Feature should all the layers be listed? Should there be one feature per layer? Or should the `layers` tag for component features be removed altogether?

**Comment by brrcrites** [comment]
@rkrishnasanka from this it seems like if we have a component that exists on N layers then we should have N features for that particular component on the output (assuming its placed). I would think that would be the ParchMint equivalent since we don't actually have layers lists (which is how I assume its handled in 3DuF).

**Comment by rkrishnasanka** [comment]
@brrcrites Yes, that's correct. Also to elaborate, the implementation in 3DuF has 3 levels of abstraction 

1. ParchMint (Components-Connections-Layers)
2. Visualization (Feature layers and the Aggregated Features) (This I directly render on the screen)
3. Manufacturing (Manufacturing Layers and partitioning the different features based on their depth and/or fabrication type)

We serialize 1 and 2 right now. I think there are a couple of things missing on (1) with regards to the spec. which we need to start fixing.

**Comment by brrcrites** [comment]
Ok, so we will output N number of component features per component, where N is the number of layers that component exists on.

Does that fully answer your question @padawong?
